server:
  port: 10005
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: Gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
      - id: uc
        uri: lb://uc
        predicates:
        - Path= /uc/**
        filters:
        - StripPrefix=1

      - id: dict
        uri: lb://dict
        predicates:
        - Path= /dict/**
        filters:
        - StripPrefix=1

      - id: websocket
        uri: lb://websocket
        predicates:
        - Path= /websocket/**
        filters:
        - StripPrefix=1

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      sensitive: false
  endpoint:
    health:
      show-details: ALWAYS