server:
  port: 8000
  address: localhost
spring:
  datasource:
    url: jdbc:mysql://192.168.204.10:3306/system?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root