spring:
  application:
    name: ConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/local

server:
  port: 10003

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 20

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      sensitive: false
  endpoint:
    health:
      show-details: ALWAYS
