server:
  port: 9000

spring:
  application:
    name: generator-ui
  datasource:
    url: jdbc:mysql://192.168.100.158:3306/build?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: jiwudev
    password: jiwudev
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    db-name: build
cola:
  devtools: #开发工具
    project-location: D:/repository/cola-cloud/cola-cloud-services/cola-cloud-autonumber
    developer: LIQIU
    table-prefix: cola_
